name: backend

services:
  postgres_db:
    image: postgres:16
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - cobra_facil_network
    volumes:
      - postgres_db_data:/var/lib/postgresql/data

  server_api:
    build:
      context: .
    container_name: server_api
    depends_on:
      - postgres_db
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    networks:
      - cobra_facil_network

volumes:
  postgres_db_data:

networks:
  cobra_facil_network:
